[TECH] Dépendances cycliques entre organization-entities et prescription/campaign (#17058)
## ☀️ Problème

Suite au merge de la PR https://github.com/1024pix/pix/pull/17022

Cette dépendance cyclique apparaît quand on démarre les workers `npm run
start:jobs`

```
ReferenceError: Cannot access 'campaignRepositories' before initialization
    at file:///Users/benjamin_petetot/dev/work/pix/api/src/prescription/campaign/domain/usecases/index.js:62:29
    at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
```

Pourtant la PR n'a rien a voir avec
`prescription/campaign/domain/usecases/index.js`.

Ça montre bien la faiblesse de notre codebase vis-à-vis des dépendances
cycliques existantes.

## ⛱️ Proposition

Voici un des cycles en cause : 
```
CYCLE PATH:
     0. src/prescription/campaign/infrastructure/repositories/index.js
     1. src/organizational-entities/application/api/organization-features-api.js
     2. src/organizational-entities/domain/usecases/index.js
     3. src/organizational-entities/infrastructure/repositories/index.js
     4. src/prescription/campaign/application/api/campaign-stats-api.js
     5. src/prescription/campaign/domain/usecases/index.js
```

Causé par l'utilisation d'API d'autres contextes dans des repositories
et injectés par des barrel-files (`index.js`) de usecases ET de
repositories. Les cycles se forment dans ces fichiers.

Modifications effectuées pour **contourner** les cycles :
- Supprimer les `index.js` qui injecte les API internes des repositories
dans `organizational-entities` et `prescription/campaign`
- Importer les API directement dans les usecases
- Utiliser des import namespace pour éviter le cycle


## 🧴 Remarques

**Les vrais problèmes sont :** 
- Le cycle de dépendance entre `organizational-entities` et
`prescription/campaigns`. `organizational-entities` ne devrait pas
dépendre de : "prescription/campaign" et
"prescription/learner-management"
- Les barrel-files (`index.js`) d'injection de dépendance.


## 🏊 Pour tester

<!--
Les instructions pour reproduire le problème, les profils de test, le
parcours spécifique à utiliser, etc.
- [ ] Documentation de la fonctionnalité (lien)
-->