[TECH] :recycle: Corrige des tests aléatoire dans le contexte du scoring de certification v2 (PIX-24158) (#17425)
## ☀️ Problème


[Message
Slack](https://1024pix.slack.com/archives/CHGPQ7W9W/p1788441834353119)

Problème détecté le 3 septembre

On a trouvé un flacky avec la commande `SEED=0.7949177792222298 npm run
test:api:unit -- --require ./tests/setup/test-random.js --bail`

```
1) Certification | Evaluation | Unit | Domain | Services | Scoring V2
       #calculateCertificationAssessmentScore
         Compute certification result for jury
           when reproducibility rate is between 50% and 80%
             should return list of competences with certifiedLevel less or equal to estimatedLevel:

      AssertionError: expected [ CompetenceMark{ …(7) }, …(3) ] to deeply equal [ CompetenceMark{ …(7) }, …(3) ]
      + expected - actual

           "assessmentResultId": [undefined]
           "competenceId": "competence_1"
           "competence_code": "1.1"
           "id": [undefined]
      -    "level": -1
      -    "score": 0
      +    "level": 0
      +    "score": 2
         }
         {
           "area_code": "2"
           "assessmentResultId": [undefined]

      at Context.<anonymous> (file:///Users/gul/Developer/1024pix/pix/api/tests/certification/evaluation/unit/domain/services/scoring/scoring-v2_test.js:1393:72)
```

@HEYGUL 

## ⛱️ Proposition


Il y a de très gros `beforeEach` qui font sans doute trop de chose, et
des tests de cas d'erreur qui laisse le système dans un mauvais état.

Extraction des deux tests d'erreurs qui laisse le système en mauvais
état : pour ne pas modifié l'état défini dans le beaforeEach

## 🧴 Remarques

<!-- Des infos supplémentaires, trucs et astuces ? -->

## 🏊 Pour tester

<!--
Les instructions pour reproduire le problème, les profils de test, le
parcours spécifique à utiliser, etc.
- [ ] Documentation de la fonctionnalité (lien)
-->